
service: api

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs12.x
  profile: charlotteremodelingcompany
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
      Resource: '*'

functions:
    hello:
        handler: handler.hello
        events:
            - http:
                  path: hello-test
                  method: GET
                  cors: true
    sendEmail:
        handler: sendEmail.handler
        events:
            - http:
                  path: send-email
                  method: post
                  cors: true
